insert into pedido_producto(descripcion, nombre_producto,stock,precio_unitario,categoria,img) 
values("Alicate de gran calidad y duracion","Alicate",100,29,"Herramietas","alicate.jpg")
values("Amoladora resistente","Amoladora",100,69,"Herrameintas","amoladora.jpg")
values("Casco de seguridad resistente a los golpes","Casco",100,5,"Seguridad","casco.jpg")
values("Clavos duraderos y no se oxidan","Clavos de Acero",100,3,"Construccion","clavos.jpg")
values("Disco de corte marca Bosh","Disco de corte",100,4,"Herramientas","disco-corte.jpg")
values("Foco philips de 14W","Foco Philips",100,15,"Iluminacion","foco.jpg")
values("Linterna a prueba de agua","Linterna",100,20,"Iluminacion","linterna.jpg")
values("Llave inglesa duradera","Llave Inglesa",100,13,"Herramientas","llave-inglesa.jpg")
values("Martillo resistente","Martillo",100,25,"Herramientas","martillo.jpg")
values("Motosierra","Motosierra",100,230,"Herramientas","motosierra.jpg")
values("","Taladro",100,79,"Herramientas","taladro.jpg")