# Generated by Django 3.1.7 on 2021-03-13 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='img',
            field=models.CharField(default='img', max_length=30),
            preserve_default=False,
        ),
    ]
