# Generated by Django 3.1 on 2022-01-20 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0002_auto_20210315_1118'),
        ('pedido', '0002_auto_20210315_2114'),
    ]

    operations = [
    ]
